version: 2.1

jobs:
  build:
    docker:
      - image: hashicorp/packer:1.7.9
    steps:
      - checkout
      - run:
          name: Packer init
          command: |
            cd packer/templates
            packer init .
      - run:
          name: Packer format source code
          command: |
            cd packer
            packer fmt -check -recursive .
workflows:
  build-ami:
    jobs:
      - build
