version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.10.2
    resource_class: small
    working_directory: ~/project/packer
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Install dependencies
          command: |
            sudo apt-get -y install unzip
            wget https://releases.hashicorp.com/packer/1.7.9/packer_1.7.9_linux_386.zip
            unzip -d packer
            ls -l packer/

workflows:
  build-ami:
    jobs:
      - build