version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.10.2
    resource_class: small
    working_directory: ~/project/packer
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Install dependencies
          command: |
            wget https://github.com/hashicorp/packer/archive/refs/tags/v1.7.9.tar.gz
            tar -xvzf v1.7.9.tar.gz
            sudo ln -s packer-1.7.9/packer /usr/local/sbin/packer
            ls -l /usr/local/sbin/
            packer -v
workflows:
  build-ami:
    jobs:
      - build