version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.10.2
    resource_class: small
    working_directory: ~/project/packer
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Install dependencies
          command: |
            wget https://releases.hashicorp.com/packer/1.7.9/packer_1.7.9_linux_386.zip
            unzip packer_1.7.9_linux_386.zip
            sudo mv packer /usr/local/bin
            rm packer_1.7.9_linux_386.zip
            packer -v

workflows:
  build-ami:
    jobs:
      - build