version: 2.1

jobs:
  build:
    docker:
      - image: hashicorp/packer:1.7.9
    steps:
      - checkout
      - run:
          name: list directory
          command: ls -la
workflows:
  say-hello-workflow:
    jobs:
      - build
