version: 2.1

jobs:
  build:
    docker:
      - image: hashicorp/packer:1.7.9
    steps:
      - checkout
      - run:
          name: Packer init & check formatting & validate template
          command: |
            cd packer/
            packer init ./templates
            packer fmt -check -recursive .
            packer validate ./templates
            
workflows:
  build-ami:
    jobs:
      - build
