version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.10.2
    resource_class: small
    steps:
      - checkout:
          path: ~/project1
      - add_ssh_keys:
          fingerprints:
            - "8c:3b:4d:31:a6:9b:a9:0b:e3:6d:c1:a6:5e:9c:4e:4f"
      - run:
          name: Clone GitHub repository1
          command: git clone git@github.com:HonkMobileCo/castle.git

workflows:
  build-ami:
    jobs:
      - build