version: 2.1

jobs:
  packer:
    docker:
      - image: hashicorp/packer:1.7.9
    resource_class: small
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Packer init
          command: packer init ./packer/templates
      - run:
          name: Packer fmt
          command: packer fmt -check -recursive ./packer
      - run:
          name: Packer validate
          command: packer validate ./packer/templates
      # - run:
      #     name: Packer build
      #     command: |
      #       cd packer
      #       packer build ./templates
workflows:
  build-ami:
    jobs:
      - packer
