version: 2.1

jobs:
  build:
    working_directory: ~/packer/templates
    docker:
      - image: hashicorp/packer:1.7.9
    steps:
      - checkout
      - run:
          name: Packer init & check formatting & validate template
          command: |
            ls -la
workflows:
  build-ami:
    jobs:
      - build
