version: 2.1

jobs:
  packer:
    docker:
      - image: hashicorp/packer:1.7.9
    resource_class: small
    working_directory: ~/project/packer
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Packer init
          command: packer init ./templates
      - run:
          name: Packer fmt
          command: packer fmt -check -diff -recursive .
      - run:
          name: Packer validate
          command: packer validate ./templates
      - run:
          name: Packer build
          command: |
            cd packer
            packer build ./templates
workflows:
  build-ami:
    jobs:
      - packer
